//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Input/PlayerControls.Inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/PlayerControls.Inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""MonsterControls"",
            ""id"": ""3d5d0678-ae00-4b51-b02a-bfac8461f5d6"",
            ""actions"": [
                {
                    ""name"": ""PressX"",
                    ""type"": ""Button"",
                    ""id"": ""639d1cf1-bfc9-49c5-8988-64e869e4eaac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressY"",
                    ""type"": ""Button"",
                    ""id"": ""5aa9ac03-4fe8-4cf3-9227-264159aa70d9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressB"",
                    ""type"": ""Button"",
                    ""id"": ""4c5308e5-5db3-483f-b7d3-778b5f24f384"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressA"",
                    ""type"": ""Button"",
                    ""id"": ""89b17fcc-296a-47b2-b2dd-fed1ebe4d7b1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""52d72499-d648-4b6c-b9ac-80f48c5087f9"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d1590bc-e96b-4f33-9130-0aa8265ca552"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6582220c-902c-41ce-a134-7769eae24393"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""195d778a-d3c8-4c2f-b66b-af53e0063ce7"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MonsterControls
        m_MonsterControls = asset.FindActionMap("MonsterControls", throwIfNotFound: true);
        m_MonsterControls_PressX = m_MonsterControls.FindAction("PressX", throwIfNotFound: true);
        m_MonsterControls_PressY = m_MonsterControls.FindAction("PressY", throwIfNotFound: true);
        m_MonsterControls_PressB = m_MonsterControls.FindAction("PressB", throwIfNotFound: true);
        m_MonsterControls_PressA = m_MonsterControls.FindAction("PressA", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_MonsterControls.enabled, "This will cause a leak and performance issues, PlayerControls.MonsterControls.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MonsterControls
    private readonly InputActionMap m_MonsterControls;
    private List<IMonsterControlsActions> m_MonsterControlsActionsCallbackInterfaces = new List<IMonsterControlsActions>();
    private readonly InputAction m_MonsterControls_PressX;
    private readonly InputAction m_MonsterControls_PressY;
    private readonly InputAction m_MonsterControls_PressB;
    private readonly InputAction m_MonsterControls_PressA;
    /// <summary>
    /// Provides access to input actions defined in input action map "MonsterControls".
    /// </summary>
    public struct MonsterControlsActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MonsterControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MonsterControls/PressX".
        /// </summary>
        public InputAction @PressX => m_Wrapper.m_MonsterControls_PressX;
        /// <summary>
        /// Provides access to the underlying input action "MonsterControls/PressY".
        /// </summary>
        public InputAction @PressY => m_Wrapper.m_MonsterControls_PressY;
        /// <summary>
        /// Provides access to the underlying input action "MonsterControls/PressB".
        /// </summary>
        public InputAction @PressB => m_Wrapper.m_MonsterControls_PressB;
        /// <summary>
        /// Provides access to the underlying input action "MonsterControls/PressA".
        /// </summary>
        public InputAction @PressA => m_Wrapper.m_MonsterControls_PressA;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MonsterControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MonsterControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MonsterControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MonsterControlsActions" />
        public void AddCallbacks(IMonsterControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_MonsterControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MonsterControlsActionsCallbackInterfaces.Add(instance);
            @PressX.started += instance.OnPressX;
            @PressX.performed += instance.OnPressX;
            @PressX.canceled += instance.OnPressX;
            @PressY.started += instance.OnPressY;
            @PressY.performed += instance.OnPressY;
            @PressY.canceled += instance.OnPressY;
            @PressB.started += instance.OnPressB;
            @PressB.performed += instance.OnPressB;
            @PressB.canceled += instance.OnPressB;
            @PressA.started += instance.OnPressA;
            @PressA.performed += instance.OnPressA;
            @PressA.canceled += instance.OnPressA;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MonsterControlsActions" />
        private void UnregisterCallbacks(IMonsterControlsActions instance)
        {
            @PressX.started -= instance.OnPressX;
            @PressX.performed -= instance.OnPressX;
            @PressX.canceled -= instance.OnPressX;
            @PressY.started -= instance.OnPressY;
            @PressY.performed -= instance.OnPressY;
            @PressY.canceled -= instance.OnPressY;
            @PressB.started -= instance.OnPressB;
            @PressB.performed -= instance.OnPressB;
            @PressB.canceled -= instance.OnPressB;
            @PressA.started -= instance.OnPressA;
            @PressA.performed -= instance.OnPressA;
            @PressA.canceled -= instance.OnPressA;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MonsterControlsActions.UnregisterCallbacks(IMonsterControlsActions)" />.
        /// </summary>
        /// <seealso cref="MonsterControlsActions.UnregisterCallbacks(IMonsterControlsActions)" />
        public void RemoveCallbacks(IMonsterControlsActions instance)
        {
            if (m_Wrapper.m_MonsterControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MonsterControlsActions.AddCallbacks(IMonsterControlsActions)" />
        /// <seealso cref="MonsterControlsActions.RemoveCallbacks(IMonsterControlsActions)" />
        /// <seealso cref="MonsterControlsActions.UnregisterCallbacks(IMonsterControlsActions)" />
        public void SetCallbacks(IMonsterControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_MonsterControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MonsterControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MonsterControlsActions" /> instance referencing this action map.
    /// </summary>
    public MonsterControlsActions @MonsterControls => new MonsterControlsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MonsterControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MonsterControlsActions.AddCallbacks(IMonsterControlsActions)" />
    /// <seealso cref="MonsterControlsActions.RemoveCallbacks(IMonsterControlsActions)" />
    public interface IMonsterControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "PressX" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPressX(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PressY" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPressY(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PressB" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPressB(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PressA" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPressA(InputAction.CallbackContext context);
    }
}
